### ISSUE TITLE
Availability on Edge

### ISSUE THREAD

**Issue by ostoh** [brunolemos/simplified-twitter#10]
Any plans on when to have the extension available on [edge](https://microsoftedge.microsoft.com/addons/search/simplified%20twitter?hl=en-GB)?

**Comment by brunolemos** [comment]
No plans at moment, unless many people ask for it.
Doesn't it support loading the `.crx` file? https://github.com/brunolemos/simplified-twitter/raw/master/chrome/simplified-twitter-extension.crx

**Comment by ostoh** [comment]
It's not possible adding the ```.crx``` file 

![Screenshot_74](https://user-images.githubusercontent.com/6714107/89010559-80fd1680-d317-11ea-86c8-16c548df5416.png)

**Comment by brunolemos** [comment]
I just tried the [Chrome](https://chrome.google.com/webstore/detail/simplified-twitter/kfopmjhmejbgomgeajemgpgpbckpoopg/related?hl=en-US) extension and it works fine on Edge. 
Edge allows you to install any extension from the Chrome Web Store:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/619186/99128894-ce617300-25ea-11eb-8f3f-c9e47dc3a191.png">

**Comment by brunolemos** [comment]
I published to Edge store but not sure there's any advantage in doing that:

https://microsoftedge.microsoft.com/addons/detail/simplified-twitter/ngkkffooahinlplicbokppbmhmdglken
