### ISSUE TITLE
Mention Menu Too Narrow

### ISSUE THREAD

**Issue by shellscape** [brunolemos/simplified-twitter#11]
See the screenshot below:

![img](https://i.imgur.com/XYnyEs5.png)

The highlighted element is being assigned a `min-width` and `max-width` that produce a mentions menu/popup that's too narrow to be useful.

**Comment by brunolemos** [comment]
Thanks for reporting. I can only reproduce if I zoom out on the browser window (Cmd -). Does it still happen to you after pessing Cmd+0?

**Comment by shellscape** [comment]
Yes, I'm at the default resolution and zoom on a 2020 16" macbook.

**Comment by rfoel** [comment]
I'm on 1920x944 and it even more narrow. 

![image](https://user-images.githubusercontent.com/19496473/100883854-9170f980-348f-11eb-8e0e-55597ecff316.png)

Min and Max width are weird:

![image](https://user-images.githubusercontent.com/19496473/100884261-0a705100-3490-11eb-82ba-9077250d80ca.png)

**Comment by sotakal** [comment]
Default 100% zoom on Firefox on Windows 10 at 1440x900 is the same issue. 90% is actually even worse, 80% is usually usable but makes the interface way too small for default usage. Increasing zoom to 110 or 120% has worked well for me.

Here are examples:
@100%
![image](https://user-images.githubusercontent.com/64089225/102629165-1116ed80-414b-11eb-8c86-360f82bb935b.png)

@90%
![image](https://user-images.githubusercontent.com/64089225/102629181-17a56500-414b-11eb-8206-b3aa0628ee8e.png)

@80%
![image](https://user-images.githubusercontent.com/64089225/102629208-1f650980-414b-11eb-83c1-8ba03d510a3c.png)

**Comment by brunolemos** [comment]
Published v1.6.0 with a fix! Let me know if it's working well for you and if you find any regression. Thanks.

**Comment by sotakal** [comment]
The latest version works fine, thank you for the quick fix!
