### ISSUE TITLE
Issue with New Tabs in v1.5

### ISSUE THREAD

**Issue by TheKins** [brunolemos/simplified-twitter#12]
It appears the fixes applied in v1.5 missed a possible cause, and it's still possible to get a stretched-out page.

**Reproduction Steps:**

1. Go to any tweet, timeline, list or other page on Twitter.
2. Middle click on a username or timestamp or other link within Twitter, to open it in a new tab.
3. Wait a second.
4. Click on that tab.

You'll find that the page has been stretched to completely fill the window, much like how the extension was faring shortly before v1.5 was released. Much like those cases, it can be fixed by either resizing the window or clicking onto another tab, then clicking back.

[Example Screenshot](https://i.imgur.com/mWLfzwe.png)

Hope this helps! Love the extension, it makes Twitter usable.

**EDIT:** I should probably mention that this was on the Chrome version of the extension.

**Comment by brunolemos** [comment]
You're right, thanks for reporting! I'll fix it soon.
