### ISSUE TITLE
Please add hide media including hiding pics

### ISSUE THREAD

**Issue by YesTrustMe** [brunolemos/simplified-twitter#16]
This is a major must-have. Pics and images on Twitter are a major annoyance. We should have a way to toggle them off and on.

**Comment by brunolemos** [comment]
Hi, all this extension do is trigger Twitter's responsive design feature, it doesn't do any other modification. Thanks

**Comment by YesTrustMe** [comment]
The naming does not imply that. I suggest changing the name to something reflecting to the "responsive design feature". 😉
