### ISSUE TITLE
Simplified for Twitter extension in Apple App Store (for macOS) cannot be downloaded

### ISSUE THREAD

**Issue by chunsj** [brunolemos/simplified-twitter#17]
As of 2022-03-06, the extension cannot be downloaded with following error messages.

"Purchage of this item is not currently available.
This item is being modified. Please try again later."

Can you check this?

**Comment by brunolemos** [comment]
I had to pay the $99 apple fee, it should be available again in a couple days

**Comment by chunsj** [comment]
Ah, I now understand what has happened. :-)

**Comment by brunolemos** [comment]
It's available again :)
