### ISSUE TITLE
Hide the view count

### ISSUE THREAD

**Issue by nikitavoloboev** [brunolemos/simplified-twitter#18]
Perhaps optionally as setting, I personally find it distracting.

This one that says 1,017 together with the icon.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/6391776/209334430-7d1314b6-739e-43de-b6f6-7fa21cc838a0.png">

Perhaps optionally as setting as I can imagine some would still want to see it.

Thank you.

**Comment by brunolemos** [comment]
Thanks for the suggestion. I also find it very distracting, but this extension don't plan offering any customizable option, it only makes twitter think it's running on a mobile screen and shows the official twitter ui for mobile without any modification.

**Comment by nikitavoloboev** [comment]
Unfortunate to hear this.

I will have to port [Minimal Theme for Twitter](https://typefully.com/minimal-twitter) as they [added support for this](https://twitter.com/linuz90/status/1606219977488334850).

Hope you reconsider.

**Comment by nikitavoloboev** [comment]
I am curious though how they made it. They said they 'didn't use CSS' for this. 🤔

I thought only way to remove things were via selectors.

**Comment by nikitavoloboev** [comment]
I was thinking of making a fork of this repo with just that feature but I could only think of doing it via CSS selectors. Is there another way you can reccomend?
