### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by brunolemos** [brunolemos/simplified-twitter#2]

**Comment by zedtux** [comment]
I'm looking for this!

**Comment by bcye** [comment]
Would love to help, already ported [Hello, Goodbye](https://github.com/bcye/Hello-Goodbye) from Chrome to safari so I think I might be able to help here.

How do you force twitter to use it's own responsive design?

**Comment by bcye** [comment]
Hi @brunolemos, I just looked into the source code, as far as I understand, you're setting the width of the window to no more than 800px, which forces twitter to use its mobile design, is that correct?

**Comment by brunolemos** [comment]
> you're setting the width of the window to no more than 800px, which forces twitter to use its mobile design, is that correct?

correct! and move things a bit to the right to centralize them

**Comment by bcye** [comment]
Ok I will create an extension and open a pull request

Bruno Lemos <notifications@github.com> schrieb am Sa. 27. Juli 2019 um
22:50:

**Comment by bcye** [comment]
Hi,

I started porting the extension though I'm running into some issues right now.
(the window.innerWidth isn't being set correctly, https://stackoverflow.com/questions/57556145/window-innerwidth-is-not-being-set)

**Comment by brunolemos** [comment]
We can't mutate the `window` object from the extension, only if we inject the script first. Browsers implement this a bit differently from each other.

I had this issue with Firefox, so I made a different implementation for them. Maybe you can use the same or we would need to come up with a third solution.

**Comment by bcye** [comment]
As far as I know, Safari is injecting the script for me

**Comment by bcye** [comment]
When I console.log the innerWidth after I update it, it reads 800

**Comment by brunolemos** [comment]
The `window` object you are setting is not the same `window` from the page. Even if the script is being injected, it may be injected using a different strategy for us to get the correct window. It's tricky, need workarounds. 

Check the `chrome` and `firefox` folders, they use two different ways of injecting the script. Maybe one of them will work with safari.

1. https://github.com/brunolemos/simplified-twitter/blob/43ada816bf01d59109c0951aeb5f8d59758a03ff/chrome/index.js#L17-L21

2.
https://github.com/brunolemos/simplified-twitter/blob/43ada816bf01d59109c0951aeb5f8d59758a03ff/firefox/inject.js#L1-L7

**Comment by bcye** [comment]
Trying the chrome version right now

**Comment by bcye** [comment]
Using the chrome version the script does get injected (visible in the elements tab) though now 
it's not conforming to the CSP:

`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

**Comment by brunolemos** [comment]
Hum yeah firefox used to give me this too when trying the chrome solution. So maybe the firefox solution with some additional workaround will be necessary. Can you open a Draft pull request with the code?

**Comment by bcye** [comment]
Holy smokes it worked!!!

**Comment by bcye** [comment]
And I was only half-expecting it.

**Comment by brunolemos** [comment]
Awesome 🎉🎉

**Comment by bcye** [comment]
PR is opened, I still need to add the logo to Safari.

**Comment by brunolemos** [comment]
I've submitted #5 to the mac app store, now we just need to wait.

![image](https://user-images.githubusercontent.com/619186/64481348-ddf85700-d1b0-11e9-869b-61b9184d1718.png)

**Comment by brunolemos** [comment]
@bcye apple rejected with two messages:

```
From Apple
2. 1 Performance: App Completeness (macOS)
4. Design: Preamble (macOS)
Guideline 2.1 - Performance


We noticed that your Safari Pane description is incomplete. Specifically, it includes placeholder text instead of accurately describing the app's features.

Next Steps

Please review your app and metadata to ensure that all of its content is final.

Design Preamble


The user interface of your app is not consistent with the macOS Human Interface Guidelines. Specifically:

We found that the app window does not contain the necessary title bar buttons. See "UI Element Guidelines: Windows" section of the Human Interface Guidelines.

Next Steps

Please revise your app to address all instances of this type of issue.

Please see attached screenshots for details.
```

1. No title bar:

![image](https://user-images.githubusercontent.com/619186/64495644-def1bd00-d272-11e9-9cf6-6f1eae21dd1c.png)

2. Placeholder text "This is a safari extension"

![image](https://user-images.githubusercontent.com/619186/64495668-182a2d00-d273-11e9-8b3c-996c1863fd4c.png)

I tried updating `NSHumanReadableDescription` but it doesn't seem to have any effect, which is weird. Do you know the reason?

**Comment by bcye** [comment]
I remember, this is an issue that I faced with Hello, Goodbye as well.
I'll do a PR that fixes them.

**Comment by bcye** [comment]
What is the NSHumanReadableDescription you wish? You need to update it in the Simplified Twitter Extension Info.plist

Further, when working with Safari extensions (at least on my machine), I need to delete DerivedData before every build, for changes to be applied (idk why).

**Comment by brunolemos** [comment]
`Remove distractions from the new twitter.`

**Comment by brunolemos** [comment]
It's available now: https://apps.apple.com/app/id1479307973?mt=12

Thanks! 

[Tweeted about it](https://twitter.com/brunolemos/status/1173749036991569921?s=20)
