### ISSUE TITLE
X/Twitter does not shrink anymore

### ISSUE THREAD

**Issue by nagato7** [brunolemos/simplified-twitter#20]
As of 21st Nov, the webpage does not shrink to 800px as the extension intended. Both Firefox/Chrome does same behaviour, so I think it's due to server-side change.
Not sure you still maintaing it, but worth the shot in either way.

**Comment by shellscape** [comment]
It looks like they updated their classnames and some of the html structure.

**Comment by brunolemos** [comment]
Thanks for reporting! This has been fixed in version 1.8.1.
