### ISSUE TITLE
Is this a copy/paste from https://github.com/thomaswangio/minimal-twitter?

### ISSUE THREAD

**Issue by cemetary** [brunolemos/simplified-twitter#3]

**Comment by brunolemos** [comment]
No, the implementations are completely different and the final result is different as well.

Minimal Twitter uses CSS to override individual components, move things around, etc. It is a bit opinionated with the developer’s personal preferences. He adds some new hover effects, etc. 

I’m not using any custom CSS. I’m just tricking Twitter to think the window is smaller, and Twitter adjusts itself automatically. It’s much less hacky and the result feels really natural.

**Comment by cemetary** [comment]
Thanks for the clarification.
