### ISSUE TITLE
Package invalid error in Brave

### ISSUE THREAD

**Issue by niksmac** [brunolemos/simplified-twitter#4]
Package is invalid: `CRX_REQUIRED_PROOF_MISSING` on Brave `Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)`

OS: MacOS Mojave 10.14.5 (18F132)

**Comment by brunolemos** [comment]
What you think is the problem?

**Comment by niksmac** [comment]
@brunolemos not sure about the cause, though I have found good amount of discussion on the same concern with chrome. Suggestion is to install the extension manually. https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/

**Comment by brunolemos** [comment]
I was getting this error with Opera too, but now I just tried with the latest code and it worked!
Can you try again? Thanks.
