### ISSUE TITLE
Could this maybe handle twitter's new animated tweet updating?

### ISSUE THREAD

**Issue by jessamynwest** [brunolemos/simplified-twitter#8]
I mostly use Twitter via my notifications. Twitter's done some new thing where the tweets update by zooming up and down for some reason. I could probably turn this off using Stylish, but if you wanted to tackle it, that would also be great.

**Comment by brunolemos** [comment]
Hi, thanks for your suggestion!

Simplified Twitter actually avoids custom CSS. The only thing it does is trick to Twitter think the window is smaller, and Twitter does everything else automatically. I don't plan add custom css since each person would suggest a different change.
